### ISSUE TITLE
Go Modules and the Packr utility

### ISSUE THREAD

**Issue by tjallingt** [gobuffalo/packr#130]
So I just made a new project
```sh
$ mkdir my-project
``` 
and initialised it with go modules
```sh
$ cd my-project
$ go mod init my-project
```
and I wanted to install the packr utility and library to be able to package my static assets.

However from the readme i find it hard to understand whether I should run 
```sh
$ go get -u github.com/gobuffalo/packr/packr
```
inside or outside of my project...

I'm also not sure whether to use packr2 since when I try to use the v2 it doesn't build because 
```sh
$ packr2 install
can't load package: package my-project:
main-packr.go:7:10: invalid import path: "D:/dev/my-poject/packrd"
Error: exit status 1
```

**Comment by relnod** [comment]
Hi, I looked into the issue with the invalid import path.
The issue seems to be, that packr2 doesn't realise, that you are using go modules.

This code is responsible for setting the import path:
```
if envy.Mods() {
	ip = ...
} else {
	ip = ...
}
```
See: https://github.com/gobuffalo/packr/blob/master/v2/jam/store/disk.go#L249-L271

The problem here is that `envy.Mods()` returns true only if  the `$GO111MODULE` environment variable is set to `on`

```
func Mods() bool {
	return Get(GO111MODULE, "off") == "on"
}
```
See: https://github.com/gobuffalo/envy/blob/7e7ddcbb431d1d9e32121d7eeee8d68bdecd7081/envy.go#L71-L73

### Temporary fix:
set `GO111MODULE` to `on`

### Real fix:
I think there are two options:
1. `envy.Mods()` also returns true, when outside the `$GOPATH`
2. If it is not desirable to change the behaviour of `envy.Mods()`, we have to implement the logic here. Maybe there is a go std package that has that logic?

**Comment by markbates** [comment]
All of the gobuffalo tool chain requires GO111MODULE=on.

That should be noted on the README.

That requirement won’t changed; FYI. You must explicitly set it.

**Comment by tjallingt** [comment]
Thanks for the reactions!

So if I understand correctly enabling `GO111MODULE` shouldn't have any downsides (as long as I don't have any existing projects depending on old module semantics) and it should make packr "just work"?

**Comment by markbates** [comment]
That’s not how Go modules currently work. They don’t let you save binaries in them yet. We all have to install any binary, not just packr using go get. That’s a go thing, not a packr thing.

**Comment by Dids** [comment]
Just researched it more and came to the same conclusion. I guess the only workaround (for now) would be to create my _own_ utility program, which would do the same as the `packr2` utility does. Thanks though, nonetheless. 👍

**Comment by markbates** [comment]
You can also call packr programatically. https://godoc.org/github.com/gobuffalo/packr/v2/jam#Pack
