### ISSUE TITLE
go.mod not found executing packr2 in subdirectory of module

### ISSUE THREAD

**Issue by simonfrey** [gobuffalo/packr#171]
## Directory setup
- go.mod
- cli/
- server/
  - routes/
  - handlers/

## Steps to reproduce

1. Execute packr2 in the `server/` directory

## Issue

packr2 tells me `go.mod cannot be read or does not exist while go module is enabled.` 
It does not find the `go.mod` that is in the directory above. For `go build` that is no problem at all.

**Comment by markbates** [comment]
That is expected behavior. Run it in the root of your project.

**Comment by Jarema** [comment]
@markbates if that is a expected behaviour, how to build with packr2 package from another directory?

lets say my `main` package is in `./cmd/app`. 

I cant build packr2 in `./cmd./app` because it cant find `go.mod`

When I use `packr2 build ./cmd/app` packr verbosity log is showing 0 boxes found. Even using absolute path for box location.

When I move the `main.go` file to root, all works as expected. But I have many binaries for the same application and I want them to sit in `./cmd/whatever`.

Is any way to do it?

**Comment by JamesCullum** [comment]
Important for other people who find this: The "project root" needs to be within GOPATH.
