### ISSUE TITLE
Packr2 does not work with dynamic box path

### ISSUE THREAD

**Issue by syifan** [gobuffalo/packr#177]
I am creating a library that needs some static assets. Packr1 works perfectly for me. However, as we move to packr2, we have to specify the path of the assets relative to the executable, which does not work in my case. So I am using this approach:

```go
_, filename, _, _ := runtime.Caller(0)
box := packr.New("BOX", path.Dir(filename))
```

When I run `packr2` in my library package, packr2 complains 

> `New` requires two arguments

, although there are two arguments provided. 

Is there a solution to this problem?

**Comment by markbates** [comment]
You can use custom stores and resolvers with packr 2.
The easiest thing for you would be to try and see if the already provided ones work for you.
For example, you might be able to use https://godoc.org/github.com/gobuffalo/packr/v2/jam/store
This video shows how to write and use custom stores and resolvers  https://www.gopherguides.tv/buffalo-resources/videos/packr-v2-0-0-walkthrough

-----------
Mark Bates

**Comment by keltia** [comment]
I have the same issue.  I have `loadResources(path string)` which takes a path (for tests mostly) and packr2 wrongly generate a box without taking the parameter into account and it does not work.  Changing this behaviour is not really welcome, v1 was also working fine there.

**Comment by markbates** [comment]
Have you tried setting the resolution directory on the box? https://godoc.org/github.com/gobuffalo/packr/v2#Box

**Comment by keltia** [comment]
It is a possible workaround but the behaviour is an unexpected one, violating POLA without an explicit warning (or I missed it).  Thanks.

**Comment by markbates** [comment]
I’m sorry you’re not happy. You’re welcome to use v1 or to open a PR with a fix. This is v2, so a lot has changed, and a major rev indicates that.

To be clear, the behavior hasn’t changed. It’s always been relative to where the box is created.

-----------
Mark Bates

**Comment by keltia** [comment]
I can admit having different expectations, maybe I was wrong before (but it worked :)).

**Comment by markbates** [comment]
it’s not a workaround, it’s there to be set for exactly these situations where dynamic paths need to be set, or if, for a variety of reasons, the path can’t be calculated automagically.

-----------
Mark Bates

**Comment by markbates** [comment]
A PR with docs explaining this use case would be very welcome.

-----------
Mark Bates

**Comment by matthijskooijman** [comment]
I was a bit confused about how packr2 works, and I suspect that confusion is the same one that sparked this issue. Perhaps my thoughts are insightful, or perhaps also terribly misguided, but even then they might be useful :-)

Say you create a box:

    box := packr.New("Foo", "./foo")

Then I would expect that the following:
 - When building using packr2 build, packr would scan the code for calls to `packr.New` and creates a box called "Foo" containing the contents of "./foo" and bundles it into the executable.
 - When running such an executable, accessing `box` looks inside the bundled data, rather than the filesystem.
 - When running without a packr2-builded executable (e.g. a plain `go build`), box is a fairly simple wrapper around the "./foo" directory.

However, I've found that in the latter case, it actually scans all go code on startup and creates boxes from there, which are later (when `packr.New` runs) looked up in the in-memory boxes map. The "./foo" argument is effectively ignored by `packr.New` (but it *is* looked at by the scanner). Looking more closely, I suspect this is to allow relative paths to work even when the current working directory is different or something like that (otoh, if the scanner knows where to look, can't the runtime `packr.New` do the same?).

I was going to argue that this scanning actually prevents dynamic paths from being passed, so if `packr.New` would just use the path passed to it, dynamic paths would automatically become possible. Thinking on this more, this only applies to the development usecase, since for the production usecase you would still need to be able to figure out *what* files to include in the binary, which probably needs some extra API anyway...
