### ISSUE TITLE
resolved using development path after every deploy

### ISSUE THREAD

**Issue by u007** [gobuffalo/packr#18]
hi,

my packr is using commit 65f7ad7a577d5fa0bf13be7ccf3cb143fef7bf9c (which is latest) as shown in my glide.lock

ive amended box.go and add in debug on method find, and found that,

when i open http://example.com/
calling is refering to my **development** path
calling: /Users/james/www/gowork/src/ossdc/actions 
path: ../public/assets
name: manifest.json 
p: /Users/james/www/gowork/src/ossdc/public/assets/manifest.json
error: Unable to open /Users/james/www/gowork/src/ossdc/public/assets/manifest.json open 

build using buffalo build -e

weird part is, when i tried to open another uri like
http://example.com/admin/
and it works!

then when i revisit  http://example.com/

Now my root also working..

what may be the issue?
and also i noticed that, when i open /admin, 
i do not get the debug message.

i suspect its already been loaded somewhere

```
func (b Box) find(name string) (File, error) {
	name = strings.TrimPrefix(name, "/")
	name = filepath.ToSlash(name)
	if _, ok := data[b.Path]; ok {
		if bb, ok := data[b.Path][name]; ok {
			bb = b.decompress(bb)
			return newVirtualFile(name, bb), nil
		}
		if filepath.Ext(name) != "" {
			return nil, errors.Errorf("could not find virtual file: %s", name)
		}
		return newVirtualDir(name), nil
	}
	p := filepath.Join(b.callingDir, b.Path, name)
	fmt.Println("find: calling", b.callingDir, "path", b.Path, "name", name, "final", p)
	f, err := os.Open(p)
	if err != nil {
		fmt.Println("Unable to open", p, err.Error())
		return nil, err
	}
	return physicalFile{f}, nil
}
```

**Comment by markbates** [comment]
This is actually both Buffalo and Packr working correctly. What's happening is you built your binary without assets using the `-e` flag. In your templates, probably `application.html` you are using either `stylesheetTag` or `javascriptTag` helpers, these helpers lookin in the assets folder (box) to find the `manifest.json` file to map the hashed file names to the simpler ones, ie `application.js` => `application.some-hash.js`. 

Because you didn't include assets in your binary, Packr does what it is supposed to do in that situation and look on disk for the file, since the file doesn't exist there either, presumably because this happening on a server, you get the error.

The solution to this problem is either to stop using the asset helper tags in your templates, or start bundling the assets in the binary.

**Comment by u007** [comment]
but shouldn't be assets path looking for files in the actual server instead of development path?

but how come templates lookup still works on server?
or template are build within the binary as well with -e option?

**Comment by markbates** [comment]
templates still work because those are bundled in the binary. the reason it's still looking at the development path is because that is where the binary was built, so that was the path that was captured.

**Comment by u007** [comment]
hi @markbates so packr is sharing assets between template and public/assets?
is there a way for me to repoint packr to use server or current running instance root path/public/assets/manifest file?
