### ISSUE TITLE
packr build not working after migrating to packr v2

### ISSUE THREAD

**Issue by nrosenberg1** [gobuffalo/packr#300]
Using Go v1.13
Until recently we have been using packr not packr2 for our release pipeline. Since packr support was removed a couple weeks ago, I'm trying to migrate us to packr2 but our build is failing.
Before we were using:
```
go get -u github.com/gobuffalo/packr/packr
go get -u github.com/gobuffalo/packr
```
so I changed this to 
```
go get -u github.com/gobuffalo/packr/packr2
go get -u github.com/gobuffalo/packr/...
```
as this was the change in usage in the README update when packr was removed.

Now our `packr2 build` command is failing. This is enterprise code so I'll have to leave out some parts. Command we're using is:
```
CGO_ENABLED=0 packr2 build -v -i -ldflags '-s -w -X {ENTERPRISE REPO PATH}.version=2.58.1 -X {ENTERPRISE REPO PATH}.buildDate=2021-12-09T01:42:42Z -X {ENTERPRISE REPO PATH}.gitCommit={COMMIT HASH} -X {ENTERPRISE REPO PATH}.gitTreeState=clean -X {ENTERPRISE REPO PATH}/install.imageTag=2.58.1-0b4c562 -extldflags "-static"' -o /home/jenkins/go/src/github.{ENTERPRISE}.com/{ENTERPRISE REPO PATH} ./tempdirectory/cmd
```
we are getting this error:
```
go build -v -i -ldflags -s -w -X {ENTERPRISE REPO PATH}.version=2.58.1 -X {ENTERPRISE REPO PATH}.buildDate=2021-12-09T01:42:42Z -X {ENTERPRISE REPO PATH}.gitCommit={COMMIT HASH} -X {ENTERPRISE REPO PATH}.gitTreeState=clean -X {ENTERPRISE REPO PATH}/install.imageTag=2.58.1-0b4c562 -extldflags "-static" -o /home/jenkins/go/src/github.{ENTERPRISE}.com/{ENTERPRISE REPO PATH} tempdirectory

can't load package: package tempdirectory: malformed module path "tempdirectory": missing dot in first path element
```

Are there other changes that need to be made for migrating to packr2 other than changing the `go get` command? Please help, thanks.

**Comment by sio4** [comment]
Hi @nrosenberg1,

Sorry to hear that. I am not sure I can provide a nice answer but let me try my best for you.

Currently, we only support go version 1.16 and 1.17, the lastest two versions, with go module on so your environment is not the best fit for buffalo and family packages. Also, packr is now not supported since we moved to use go's native `embed` package for the same purpose. Since now go supports file embedding natively, we may not support packr and packr2 anymore.

We recently changed the directory structure (merge `packr2` into the root and just use version tag for module versioning) of packr to resolve self reference issue, but the change made on packr2 from packr already happened a few years ago so your code migration issue could be related to the changes rather than recent change.

However, I understand the recent change made referencing the older version harder when if you still use `GO11MODULE` off and use `GOPATH` mode. So I wonder if you can migrate your project to use go module then I think the old code with packr would work.

Another approach I would suggest is using `go get` command with branch selection. Actually, the original tree which contains packr v1 is still in https://github.com/gobuffalo/packr/tree/fix-update-deps so I guess the following command will grab the old tree into your module path.

```console
$ go get github.com/gobuffalo/packr/packr@fix-update-deps 
```

However, I highly recommend that you would better migrate your project to the recent version of go, 1.17 or at least 1.16, and could also try to migrate your code from packr to embed.

**Comment by nrosenberg1** [comment]
Hi @sio4 thank you for the advice.

We got around migrating by manually downloading and old release version and our pipeline now works as before. We will migrate to a more recent version of go in the future. Thank you again for the advice.
