### ISSUE TITLE
packr not detecting files even though it is in the binary

### ISSUE THREAD

**Issue by yadunut** [gobuffalo/packr#71]
# Packr Test

This repository was created to test out an error I got when using packr. 

## Usage

```Bash
go get -d github.com/yadunut/packr-test/...
```

or 

```
git clone https://github.com/yadunut/packr-test
```

## No Issues

```bash
cd packr-test
packr build cmd/server/main.go
./main
```

### Expected

```
Init Function
2 files in ./templates
ListFiles function
Files in box:
index.tmpl
register.tmpl
```

### Actual

```
Init Function
2 files in ./templates
ListFiles function
Files in box:
index.tmpl
register.tmpl
```

## Issues

Changed the path to the repository

```bash
cd ..
mv packr-test packr-tests
cd packr-tests
./main
cd ..
mv packr-tests packr-test
cd packr-test
```

### Expected

```
Init Function
2 files in ./templates
ListFiles function
Files in box:
index.tmpl
register.tmpl
```

### Actual

```
Init Function
0 files in ./templates
ListFiles function
Files in box:
index.tmpl
register.tmpl
```

## What Happened?

The init function doesn't detect files in the binary, but detects files when they're in the folders. 

Outside of the init function, there are no issues.

**Comment by markbates** [comment]
Can you post some working code that reproduces this? I think you’re Error is actually in using the Go templates based on the error, but without seeing some code, or more complete steps to repo its hard to tell for sure.

**Comment by ravernkoh** [comment]
I think the working code is [in the repository](https://github.com/yadunut/packr-test) he asked us to `go get`.

**Comment by yadunut** [comment]
I've updated the issue. So what happened was that the init function does not detect files that are in the  binary, but only detects files that are there physically.

**Comment by dak0rn** [comment]
I think I have the same problem which is reproducible by renaming a folder with assets after building. However, it only happens when running `packr build`. When I use `packr` to generate `.go` files and then run `go build`, it works as expected.

@yadunut you could try the same with your test repository to see if that's the same issue.

**Comment by markbates** [comment]
@yadunut when running your repo (thanks by the way), I can see that the files are actually there. The problem only seems to occur when you're trying to read the content of the box during an `init` function. My guess, after spending quite a lot of my evening looking at this is that the problem is more related to the way `init` works more than anything else.

I'm at a bit of loss for how to proceed with this ticket. Part of me wants to say `init` functions aren't guaranteed to run in a particular order, therefore relying on them to do so, (in this case load the templates before calling - surprise, it doesn't), isn't correct. I can verify, that through the use of print statements I'm seeing the box be initialized after you're accessing it. So part of me wants to close the ticket as I don't a) think there's a good fix for it and b) because this is an issue with `init` and not packr.

The other part of me wants to keep it open, but I'll be honest, I'm not going to put anymore time into this particular issue since the problem is `init` related, and can be worked around through design, or other choices, much like all issues with `init`.

Please don't think I'm blowing this issue off, but I unless someone else wants to take a crack at it, I won't be. Sorry.

**Comment by ravernkoh** [comment]
Your fix involves making sure the packr files get passed to the compiler first?

**Comment by markbates** [comment]
It’s the only fix possible. The problem isn’t with packr, but with the way `init` works.

**Comment by ravernkoh** [comment]
Hmm, seems kind of hacky and it also affects those that don't have these issues because now all of their files will have `a_` in front. Do you think it would be better to have a flag which activates this behaviour? I would be happy to submit a PR.

**Comment by markbates** [comment]
It is hacky. I wasn’t going to fix this issue because the problem isn’t Packr, but using rather due to the way init works in Go.

Enough people complained, so I “fixed” the problem. I can’t fix the way Go works, but I can do what the spec says and put the stuff that needs to be initialized first; first.

I’m sorry you don’t like the prefix, neither do I.

You are welcome to submit a PR to disable the prefix, but it’s here to stay otherwise.

--
Mark Bates

**Comment by ravernkoh** [comment]
Oh, I'm not unhappy that the fix is hacky because I too angry that there is really no choice here. I was just thinking of a cleaner solution. Sorry if you got the wrong idea. I'll submit a PR soon :)

**Comment by markbates** [comment]
lol fair enough. And for the record; it is hacky, and I’m not a fan, but it’s the “safer” option. Most don’t check in the files, so it’s not a big deal. Those of us that do, I do, because of vgo, then yeah, it’s a bit of a drag.

--
Mark Bates
