### ISSUE TITLE
Packr not able to locate files in binary

### ISSUE THREAD

**Issue by dakait** [gobuffalo/packr#93]
I have a project structure as 
.
├── db
│   └── migrations
│       ├── mysql
│       │   ├── 00001_init.sql
├── main.go
├── models
│   ├── database.go

in database.go file I have initialized made a global box variable: 
`var box packr.Box `
and initialized a packr box in init() function:
`box = packr.NewBox(migrationFolder)     //migrationFolder = "../db/migrations"`

I'm listing the files in box in another function:
```
func foo() {
	files := box.List()
        var myfile []string
	for _, file := range files {
		if strings.HasPrefix(file, "mysql") {
			myfile = append(myfile, file)
		}
	}
	sort.Strings(myfile)
	log.Println(myfile)
}
```

When I'm working on local everything works fine but when I use the binary created by packr install to some other computer, the "myfile" variable is empty slice. 
Please help me is there something I'm missing?

**Comment by markbates** [comment]
How do you build your binary? and how/where is your box defined? Are you using the latest version?

**Comment by dakait** [comment]
1. I use the command line tool:
`packr install`
2. Box is defined in ./models/database.go inside an init function (see directory structure for reference)
3. Yes I'm using the latest version

**Comment by dakait** [comment]
Actually, I figured out the bug in my code. I was using a **global string variable** named _migrationFolder_ to pass directory into `packr.NewBox()` and things were not working.

**This didn't work:**   `box = packr.NewBox(migrationFolder) //migrationFolder = "../db/migrations"`
**This worked:**         `box = packr.NewBox("../db/migrations")`
I want to know **why?**

**Comment by markbates** [comment]
This was closed because it was related to an `init` bug, that has been resolved, and not due to variable usage.

The example app shows all of the ways Box's can be defined and which types of variables, constants, and such can/can not be used.

https://github.com/gobuffalo/packr/blob/master/example/example.go#L17

**Comment by abenz1267** [comment]
Thanks for the clarification. Not sure if it fits in here, because i have a similar issue:

I'm using packr in a library. i have to modify the `runtime.Caller(1)` from 1 to 4, so "./public" actually picks up the "public" folder where the main function is instead of looking for a "public" folder close to the functions file. 

Am i missing something?

**Comment by markbates** [comment]
Can you open an issue with a reproducible example? Include the version you’re using etc....

Make sure you’re on the latest version first before opening the issue. :)

There are also betas of v2 you can test to see if that resolves your problem.
